# This is a basic workflow to help you get started with Actions

name: CI

permissions:
  contents: read
  statuses: write

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - run: echo "${{ toJSON(github) }}"
    - run: gh api
        --method POST
        /repos/${{ github.repository }}/statuses/${{ github.sha }}
        -f state='success'
        -f target_url='https://example.com/build/status'
        -f description='The build succeeded!'
        -f context='continuous-integration/jenkins'
      env:
        GH_TOKEN: ${{ github.token }}
