name: Test Coverage

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Run tests with coverage
        run: |
          go test -v -coverprofile=coverage.out -covermode=atomic
          go tool cover -func=coverage.out | tee coverage.txt

      - name: Extract coverage percentage
        id: coverage
        run: |
          COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')
          echo "percentage=$COVERAGE" >> $GITHUB_OUTPUT
          echo "Coverage: $COVERAGE%"

      - name: Upload coverage data
        uses: actions/upload-artifact@v4
        with:
          name: coverage-data
          path: |
            coverage.out
            coverage.txt
          retention-days: 1

      - name: Save PR metadata
        run: |
          echo "${{ github.event.pull_request.head.sha }}" > pr_sha.txt
          echo "${{ github.event.pull_request.number }}" > pr_number.txt

      - name: Upload PR metadata
        uses: actions/upload-artifact@v4
        with:
          name: pr-metadata
          path: |
            pr_sha.txt
            pr_number.txt
          retention-days: 1
